### ISSUE TITLE
facing errors

### ISSUE THREAD

**Issue by Gingsen** [itohan-uk/MySWEspace#1]
hi, can you please aid me. i keep getting these errors to the extent i even copied your code from github but it still shows same errors

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Ginsgen\AppData\Local\Programs\Python\Python39\lib\tkinter\_init__.py", line 1892, in __call_
    return self.func(*args)
  File "d:\Python workss\grandmas_kitchen.py", line 45, in __run_search_query
    recipe = self.__get_recipe(query)
  File "d:\Python workss\grandmas_kitchen.py", line 73, in __get_recipe
    for recipe in query_result:
  File "C:\Users\Ginsgen\AppData\Local\Programs\Python\Python39\lib\site-packages\py_edamam\__init__.py", line 101, in search_recipe
    yield Recipe(edamam=self, **data)
TypeError: __init__() got an unexpected keyword argument 'cuisineType'

**Comment by hectic12** [comment]
Have you installed the necessary libraries? pytube, tk, and playsound?

**Comment by itohan-uk** [comment]
> Have you installed the necessary libraries? pytube, tk, and playsound?

@hectic12 yes I installed the necessary libraries. 

```
pip3 install tkinter
pip3 install playsound
pip3 install PyObjC
pip3 install install requests
pip3 install py-edamam
```
